language: python

python:
  - "2.7"
  - "3.3"

env:
  - DJANGO=1.5.9
  - DJANGO=1.6.6

install:
  - pip install -q Django==$DJANGO
  - pip install -q flake8
  - pip install -q python-coveralls coverage
  - python setup.py install

before_script:
  - make flake8

after_success:
  - make coveralls

script:
  - make coverage
